### ISSUE TITLE
Gauge disappear when adjusting panel size

### ISSUE THREAD

**Issue by talbaror** [briangann/grafana-gauge-panel#3] opened 2016-10-22 20:07 UTC
Hello,
First very nice and useful plug-in, i run into issue on two different Grafana 3.1.1  system with D3 Gauge plugin installed , when i try to set the panel by adjusting it to the right size after setting the metric to display the Gauge is disappear and could not be shown again , until i recreate it but cannot adjust it in any way.
Any idea ?
Thanks

**Comment by briangann** [comment] 2016-10-24 01:39
Which browser does this happen on? It should scale/adjust automatically, or you can specify the width/height manually.  I haven't seen the gauge vanish though.

**Comment by briangann** [comment] 2016-11-02 01:49
I reproduced this when setting the Height under "general" then removing it. That causes the whole gauge to vanish (you can still see some of the dial marks in black).  Putting a size back into "Height" (any size 100px) restores it to the default height.

Is that what you are seeing? 

It looks like the panel is not using the "row" height either and is just bleeding over it.

If you have a screenshot that would help :)

Thanks!

Brian

**Comment by briangann** [comment] 2016-11-25 03:54
A fix for this has been checked in, will work on the other issues before merging and updating.

Thanks!

**Comment by briangann** [comment] 2017-02-11 05:30
fix for this has been merged, closing

**Closed by briangann** 2017-02-11 05:30 UTC
